### ISSUE TITLE
SG-as-a-library: can't read Vars during inserts

### ISSUE THREAD

**Issue by frederikhors** [dosco/super-graph#102]
I'm using this code:

```go
func NewConfig() core.Config {
	return core.Config{
		DefaultBlock: true,

		Blocklist: []string{
			"password",
			"account_id",
    },

		Vars: map[string]string{
			"account_id": "sql:select account_id from users where id = $user_id",
    },

		Roles: []core.Role{
			{
				Name: "user",
				Tables: []core.RoleTable{
					{
						Name: "players",
						Query: &core.Query{
							Filters: []string{
								"{ account_id: { _eq: $account_id } }",
							},
						},
						Insert: &core.Insert{
							Presets: map[string]string{
								"account_id": "$account_id",
							},
						},
					},
				},
			},
		},
	}
}
```

What is not working here is:

```go
Insert: &core.Insert{
	Presets: map[string]string{
		"account_id": "$account_id",
	},
},
```

The error is:

`error="required variable 'account_id' of type 'bigint' must be set"`

It works if I use this:

```go
Insert: &core.Insert{
	Presets: map[string]string{
		"account_id": "123",
	},
},
```

and works if I use the "global" `$user_id` var, but of course this is wrong.

Should I think SG can't read `Vars map[string]string` in `Insert` hooks?

**Comment by frederikhors** [comment]
@dosco no pressure on other issues, but this is blocking me.

Can you take a quick look and tell me if I'm wrong?

**Comment by frederikhors** [comment]
Oh! Wow! I just found that it works if you use this:

```go
Insert: &core.Insert{
	Presets: map[string]string{
		"account_id": "sql:select account_id from users where id = $user_id",
	},
},
```

But this is DRY... :(

**Comment by dosco** [comment]
I'm trying to discourage use of SQL. This feature was a compromise early since someone needed it and I didn't want to be a blocker. I want all the this to be GraphQL and all the SQL be generated so the software has full control and no room for broken SQL breaking things. Also there is this method to help you set https://pkg.go.dev/github.com/dosco/super-graph@v0.14.31/core?tab=doc#Config.AddRoleTable

**Comment by dosco** [comment]
> Oh! Wow! I just found that it works if you use this:
> 
> ```go
> Insert: &core.Insert{
> 	Presets: map[string]string{
> 		"account_id": "sql:select account_id from users where id = $user_id",
> 	},
> },
> ```
> 
> But this is DRY... :(

Any suggestions on how to improve this?

**Comment by frederikhors** [comment]
This, for now, is my biggest problem to face in order to move definitively to SuperGraph.

Several Rails applications we have in production use https://github.com/influitive/apartment for the `account_id` and we need this clause everywhere: in the insertions (with the preset, like in this case) and in the remaining CRUD operations (as a `where` clause).

I would be very happy not only to be able to solve this specific problem, also if **SuperGraph can have a global solution to the management of the `account_id` (tenant)**.

**Comment by frederikhors** [comment]
> I'm trying to discourage use of SQL.

I agree. I want it too.

Can we proceed step by step?

Can we first solve this problem (reading the "global" `Vars` (`sql` or not)) and then find a more effective way to completely remove the use of manual `sql` from SG?

**Comment by dosco** [comment]
> Can we first solve this problem (reading the "global" Vars (sql or not)) and then find a more effective way to completely remove the use of manual sql from SG?

Can you define the problem?

**Comment by frederikhors** [comment]
> Can you define the problem?

The problem in the first post:

Using this code:

```go
Insert: &core.Insert{
	Presets: map[string]string{
		"account_id": "$account_id",
	},
},
```

with `$account_id` defined in `Vars`:

```go
Vars: map[string]string{
  "account_id": "sql:select account_id from users where id = $user_id",
},
```

it doesn't work:

```log
error="required variable 'account_id' of type 'bigint' must be set"
```

Using this instead works:

```go
Insert: &core.Insert{
	Presets: map[string]string{
		"account_id": "sql:select account_id from users where id = $user_id",
	},
},
```

**Is there a way to avoid the repetition of `sql:select account_id from users where id = $user_id`, using the `Var` in `Presets`?**

**Comment by dosco** [comment]
Fixed https://github.com/dosco/super-graph/commit/3967dcc3242050b93881aac09a588f94373b11a8
