### ISSUE TITLE
URGENT URGENT URGENT err == nil BUG from v0.14.32

### ISSUE THREAD

**Issue by frederikhors** [dosco/super-graph#107]
Starting from `v0.14.32` this doesn't work anymore:

```go
func MyHandler() {
  ...

  result, err := superGraph.GraphQL(ctx, query, variables)
  
  if err != nil {
    println(err) // err is nil, result is the error!!!

    http.Error(w, "internal error", 500)

    return
  }

  // it continues here!!!
}
```

If I use a wrong query on purpose and I expect the `err != nil` it's not! It's `nil`!!!

`result` is the error here!

**BUG!**

**Comment by dosco** [comment]
What do you mean by wrong query and is this with the allow list enabled (aka production mode) ?

**Comment by dosco** [comment]
Fixed https://github.com/dosco/super-graph/commit/9e97ad2086d72e340e8b23e36c0d421b5487f331

**Comment by dosco** [comment]
Sorry lots of changes going on will add more tests.

**Comment by frederikhors** [comment]
> What do you mean by wrong query

A wrong query on purpose, eg. an non existent table

> is this with the allow list enabled?

Yes. Nothing is changed in my code. Only updated from `v0.14.30` to `v0.14.32` and this is wrong.

**Comment by frederikhors** [comment]
> Sorry lots of changes going on will add more tests.

Ok. It would be amazing to have smaller commits. To better understand this issues.

Thanks for your work, @dosco!!! :)

**Comment by dosco** [comment]
Soon I'll lock things down a little more once we hit v1. In the meanwhile you can lock the versions in your mod file.
