### ISSUE TITLE
From v0.14.32 this code is not working anymore

### ISSUE THREAD

**Issue by frederikhors** [dosco/super-graph#108]
From `v0.14.32` this code is not working anymore

```go
Tables: []core.Table{
  {Name: "me", Table: "users"},
},
```

error:

`error="table not found for selector: me"`.

Same code with `v0.14.31` works.

**Comment by dosco** [comment]
Do you have a blocklist?

**Comment by frederikhors** [comment]
Oh! Wow! This was the problem! My blocklist was:

```go
"password",
"account_id",
"tokens",
"token",
"users",
"user",
```

**Comment by frederikhors** [comment]
But this is a problem now if I have a column called this way, right?

**Comment by dosco** [comment]
It is a general blocklist for now. I could add one for tables and one for columns

**Comment by dosco** [comment]
Fyi you don't really need to use blocklist in production the allow list ensures only saves queries ca. Be run no one can add cloumns or modify the query in any way from the client
