### ISSUE TITLE
From v0.14.32 "invalid foreign key table" if table name in Blocklist

### ISSUE THREAD

**Issue by frederikhors** [dosco/super-graph#109]
### What version of Super Graph are you using?

`v0.14.35`

### Steps to reproduce the issue (config used to run Super Graph)

Using this config:

```go
core.Config{
  Debug:        !IsProduction,
  UseAllowList: IsProduction,
  DefaultBlock: true,
  Blocklist: []string{
    "password",
    "account_id",
    "accounts",
  },
  Tables: []core.Table{
    {Name: "me", Table: "users"},
  },
  Vars: map[string]string{
    "account_id": "sql:select account_id from users where id = $user_id",
  },
  Roles: []core.Role{
    {
      Name: "user",
      Tables: []core.RoleTable{
        {
          Name: "me",
          Query: &core.Query{
            Filters: []string{
              "{ id: { _eq: $user_id }",
            },
          },
        },
        {
          Name: "teams",
          Query: &core.Query{
            Filters: []string{
              "{ account_id: { _eq: $account_id } }",
            },
          },
        },
        {
          Name: "players",
          Query: &core.Query{
            Filters: []string{
              "{ account_id: { _eq: $account_id } }",
            },
          },
          Insert: &core.Insert{
            Presets: map[string]string{
              "account_id": "sql:select account_id from users where id = $user_id",
            },
          },
          Update: &core.Update{
            Presets: map[string]string{
              "account_id":  "sql:select account_id from users where id = $user_id",
              "updated_at": "now",
            },
          },
        },
      },
    },
  },
}
```

### Expected behaviour and actual result

I expect this to work _(it was working with `v0.14.31`)_, but it gives an error instead:

`PNC  error="invalid foreign key table 'accounts'"`

I think this is happening because of:

```go
Blocklist: []string{
  "password",
  "account_id",
  "accounts", // this line
},
```

and I know I can use this instead:

```go
{
  Name: "accounts",
  Query: &core.Query{
    Block: true,
  },
  Insert: &core.Insert{
    Block: true,
  },
  Update: &core.Update{
    Block: true,
  },
  Delete: &core.Delete{
    Block: true,
  },
},
```

but as you can see **this is repetitive and error-prone**.

### Ideas

[Here](https://github.com/dosco/super-graph/issues/108#issuecomment-653700244) you said, @dosco, you are thinking of creating two blocklists, one for tables and one for columns.

And I agree a lot.

### Additional

When using `Blocklist` the tables are not showing in introspection info.

When using `Block: true` instead they are.

**I think they should not in both cases.**

### Concerns

I know in production it's impossible to query something not in `allow.list` but also **this is error-prone and potentially dangerous** and can lead to the **exclusion of SuperGraph from the choices** for some high-security projects (you have to convince the boss who finally decides).

I'll explain it better:

When some programmers on the project are trying the queries locally and SuperGraph updates the `allow.list` file, it can happen that inadvertently (_I know it shouldn't happen, but it does_) that file is put into production.

And the damage is done! 💀💀💀

So **I would prefer to lock the tables by configuration**.

**Comment by frederikhors** [comment]
I know in production it's impossible to query something not in `allow.list` but also this is error-prone and potentially dangerous and can lead to the exclusion of SuperGraph from the choices for some high security projects.

I'll explain it better:

When some programmers on the project are trying the queries locally and SuperGraph updates the `allow.list` file, it can happen that inadvertently (I know it shouldn't happen, but it does) that file is put into production.

And the damage is done.

**So I would prefer to lock the tables by configuration.**

**Comment by dosco** [comment]
I see the problem currently blocked tables are just excluded from the schema and this is breaking the code that walks the relationship graph between tables since it can't find the foreign key table `accounts`. I'll fix this. We should just throw an error in development when blocked tables are used, we currently do this when blocked columns are used. 

```
{
  Name: "accounts",
  Query: &core.Query{
    Block: true,
  },
  Insert: &core.Insert{
    Block: true,
  },
 ...
},
```

This above code is not the same as the block list, it does not block columns or tables from being used it only blocks operations. Also to prevent repeating yourself you can mark the role tables as read-only `read_only: true`. I can look into how operations are exposed in introspections and see if we can block those.

```
{
  Name: "accounts",
  read_only: true,
  Query: &core.Query{
    Block: true,
  },
```
}

Also yes separate block lists might be good.

**Comment by frederikhors** [comment]
I love you, @dosco.

**Comment by dosco** [comment]
I have been thinking about this and it's a complex problem. 

1. Does blocking mean we block the tables and columns entirely as of they never existed or just hide and throw errors?

2. If blocked means drop from the original schema then blocking primary key columns like 'id' would break relationships between tables. We could log a message to the console when this happens.

3. If blocked means hidden then should  they be allowed in where clauses etc. 

4. Hideing the columns and throwing errors all over the place is hard and can  be prone to holes. While just dropping the column or table when the schema is read in and logging issues like primary key blocked is easier and more solid.

5. For hiding columns on tables we already have the allowed columns option.

**Comment by dosco** [comment]
Improvements to blocking however it's still a single list for now.
https://github.com/dosco/super-graph/commit/f7d26e67e4042776d176a972e26111aa8c211ff9

1. Blocks tables, columns and functions from introspection and queries
2. Columns are blocked even when used in `where` clauses expect for in filters set in the config file
