### ISSUE TITLE
Disable functions by default

### ISSUE THREAD

**Issue by frederikhors** [dosco/super-graph#111]
**What would you like to be added**:

I think we should disable functions by default and have `EnableFunctions` like this:

```go
{
  Name: "players",
  Query: &core.Query{
    EnableFunctions: true, // default false
  },
},
```

**Why is this needed**:

Because it is used less and for less tables in a medium-sized project.

And we can increase development speed by decreasing SuperGraph background operations.

**Comment by dosco** [comment]
> And we can increase development speed by decreasing SuperGraph background operations.

Functions are not just functions defined in Postgres they are also aggregation operations like `sum`, `count`, etc which is not uncommon. There is no impact on background performance by keeping them enabled.

**Comment by frederikhors** [comment]
Ok.

I wrote it because in my case - a medium-sized project - with 30 tables - I use the aggregate functions for only two tables.

**Comment by dosco** [comment]
I'll think on this some more.

**Comment by dosco** [comment]
I can't think of a reason to add this friction to function usage. I'll close for now if this is causing any specific issue in the future either re-open or  start a new issue.
