### ISSUE TITLE
Query with order_by from browser error: "expecting an object"

### ISSUE THREAD

**Issue by frederikhors** [dosco/super-graph#114]
### What version of Super Graph are you using?

`v0.14.35`

### Steps to reproduce the issue (config used to run Super Graph).

I'm trying to query with this payload (from browser):

```json
{
  "query": "query players($order_by: playerOrderBy!) {
    players(order_by: $order_by) {
      id
      created_at
    }
  }",
  "operationName": "players",
  "variables": {
    "order_by": {
      "id": "desc"
    }
  }
}
```

### Expected behaviour and actual result.

It gives me error:

```log
ERR  error="expecting an object"
```

**Why?**

**Comment by dosco** [comment]
Order By requires you to set specific indexes on the database so the order has to be deliberate. Also changing the order invalidates the pagination cursor. In short since we generate a SQL query and re-use it in production and since ORDER BY cannot be a parameter in SQL this can't be done easily or without hurting performance. I'll think over this some more but closing for now.

**Comment by frederikhors** [comment]
> Order By requires you to set specific indexes on the database so the order has to be deliberate.

Sorry for my ignorance in databases.

I have already set the indexes on the DB for the columns on which I want to leave the user free to order.

> Also changing the order invalidates the pagination cursor.

It doesn't matter to me because when the user changes the order he knows that the cursor is invalidated and "starts over".

---

I think this is another good case for a "special function" "without pre-compiled scheme" that allows this kind of user queries comfortable but (perhaps) slower.

Like in #115.

**Comment by dosco** [comment]
Below is how I do similar things in my apps. I'm still thinking on how to make variables work with `order_by` and `limit` not against implementing it just need to figure out a good solution. 

```
fragment Player on players {
  id
  created_at
}
```

```
query getPlayersDesc {
  players(order_by: { id: desc }) {
    ...Player  
  }
}
```

```
query getPlayersAsc {
  players(order_by: { id: asc }) {
    ...Player  
  }
}
```

**Comment by frederikhors** [comment]
The problem I have is to `ORDER BY` and filter with `WHERE` in a completely dynamic way.

### Example

Take Github's issues page > Sort menu, what I need is very similar:

![image](https://user-images.githubusercontent.com/41120635/86768864-7c15b180-c04e-11ea-9662-18005ddc5488.png)

I can sort results by many columns (even by reactions!).

### Another example

In this tutorial here: https://www.howtographql.com/react-urql/7-pagination-and-cache-updates/ they use this query:

```js
export const FEED_QUERY = gql`
  query FeedQuery($first: Int, $skip: Int, $orderBy: LinkOrderByInput) {
    feed(first: $first, skip: $skip, orderBy: $orderBy) {
      count
      ...
    }
  }
`
```

And they use `variables` object:

```js
const variables = React.useMemo(() => ({
  skip: isNewPage ? (page - 1) * 10 : 0,
  first: isNewPage ? 10 : 100,
  orderBy: isNewPage ? 'createdAt_DESC' : null
}), [isNewPage, page])
```

[Here the code](https://github.com/howtographql/react-urql/blob/master/src/components/LinkList.js)

### Another example

Here a user is trying to solve the same problem using [sqlc](https://github.com/kyleconroy/sqlc):

https://github.com/kyleconroy/sqlc/issues/364#issuecomment-593100103

> I need to select on t1, which the filters are determined from UI, so I need any combination of filters, it means I should support following 9 queries on my back-end.
> Users can also sort on any column they wish (ASC/DESC).
> Which is 9*4 = 36 different possible queries for a table with 2 fields.

---

As you can see I need to sort the results not only by one column but many.

**And creating so many javascript queries is wasteful and counterproductive.** Which is the opposite of what SuperGraph would like to achieve: 100% productivity. :smile:

**Comment by frederikhors** [comment]
I think we can close this in favor of #120.
