### ISSUE TITLE
When no row is found return an object, do not throw an error

### ISSUE THREAD

**Issue by frederikhors** [dosco/super-graph#121]
**What would you like to be added**:

Maybe we should not throw an error when no row is found.

**Why is this needed**:

Today SuperGraph as a library throws in this case with:

```log
error="sql: no rows in result set"
```

Maybe we should answer with this instead:

```json
{
  "errors": [
    {
      "message": "not found",
      "path": [
        "player"
      ]
    }
  ],
  "data": null
}
```

I think this is more corresponding with what all the other GraphQL backends return and all the GraphQL clients expect in response.

And even if I'm not an expert in GraphQL syntax, I think this is what is foreseen by the standard.

What do you think?

**Comment by dosco** [comment]
Good point i'll take a look

**Comment by kpbird** [comment]
I am not expert of GraphQL but Hasura respond following if no rows

`{
  "data": {
    "todo": []
  }
}`

**Comment by frederikhors** [comment]
Thanks @kpbird.

**Comment by kpbird** [comment]
I am not able to reproduce with the following code. Can you please help me to reproduce this bug

```
package main

import (
	"context"
	"database/sql"
	"fmt"
	"log"

	"github.com/dosco/super-graph/core"
	_ "github.com/jackc/pgx/v4/stdlib"
)

func main() {
	db, err := sql.Open("pgx", "postgres://postgres:postgres@localhost:5432/app_development")
	if err != nil {
		log.Fatal(err)
	}

	sg, err := core.NewSuperGraph(nil, db)
	if err != nil {
		log.Fatal(err)
	}

	query := `
             query {
	         	products(where:{id: { eq: 5000 }}) {
		          name
		       }
	      }`

	ctx := context.Background()

	res, err := sg.GraphQL(ctx, query, nil)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(string(res.Data))
}

```

Output

`{"products": []}`

**Comment by frederikhors** [comment]
I'm using this query:

```json
query player($id: ID!) {
  player(id: $id) {
    id
    created_at
  }
}
```

with this payload:

```json
{
  "query": "query player($id: ID!) {\n  player(id: $id) {\n    id\n    created_at\n  }\n}\n",
  "variables": {
    "id": "123456" // does not exist
  },
  "operationName": "player"
}
```

SuperGraph throws an error:

```log
error="sql: no rows in result set"
```

**Comment by kpbird** [comment]
Still not able to reproduce the error with below code. 
Which method are you using to pass query, variables and operationName as JSON?


```
package main

import (
	"context"
	"database/sql"
	"fmt"
	"log"

	"github.com/dosco/super-graph/core"
	_ "github.com/jackc/pgx/v4/stdlib"
)

func main() {
	db, err := sql.Open("pgx", "postgres://postgres:postgres@localhost:5432/app_development")
	if err != nil {
		log.Fatal(err)
	}

	sg, err := core.NewSuperGraph(nil, db)
	if err != nil {
		log.Fatal(err)
	}

	query := `
	       query($id: ID!) {
		     products(id: $id) {
		        name
		         created_at
		    }
	  }`

	variables := []byte(`
	       {
		      "id":"1000"
	       }
	`)

	ctx := context.Background()

	res, err := sg.GraphQL(ctx, query, variables)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(string(res.Data))
}

```

Output

```
{"products": []}
```

I have tried the same with UI not the same response 

<img width="1438" alt="Screenshot 2020-07-07 at 9 24 21 PM" src="https://user-images.githubusercontent.com/870344/86808385-6f1db000-c098-11ea-90a5-47e74c6f6ae6.png">

**Comment by frederikhors** [comment]
I got the point.

I'm using this:

```go
res, err := superGraph.GraphQL(ctx, body.Query, body.Variables)

if err != nil {
  http.Error(w, http.InternalServerError, http.StatusInternalServerError)
  return
}
```

You are printing `res.Data` which is `nil` or an empty `[]`.

Is your line:

```go
if err != nil {
  log.Fatal(err)
}
```

getting called?

**Comment by kpbird** [comment]
following line doesn't execute because err is nil
```
if err != nil {
  log.Fatal(err)
}
```

to verify I write following code

```
fmt.Println(err == nil)
fmt.Println(string(res.Data))
```
Output

```
true
{"products": []}
```
output true is for err variable,  `res, err := sg.GraphQL(ctx, query, variables)` method doesn't throw an error

Which method are you using to pass the following payload because of sg.GraphQL accept three arguments context, query and variables.

```
{
  "query": "query player($id: ID!) {\n  player(id: $id) {\n    id\n    created_at\n  }\n}\n",
  "variables": {
    "id": "123456" // does not exist
  },
  "operationName": "player"
}
```

**Comment by dosco** [comment]
Fixed in https://github.com/dosco/super-graph/commit/4f142ff08a50804f8137484e50cf92ea25e40b7b

**Comment by frederikhors** [comment]
@kpbird, now I see the difference.

You are using this:

```go
query := `
  query($id: ID!) {
    products(id: $id) {
      name
      created_at
    }
  }
`
```

I'm using this instead:

```go
query := `
  query($id: ID!) {
    product(id: $id) {
      name
      created_at
    }
  }
`
```

(note `products` > `product`).

@dosco, it works now.

Thanks. :smile:
