### ISSUE TITLE
Add SG on graphql.org website

### ISSUE THREAD

**Issue by frederikhors** [dosco/super-graph#122]
**What would you like to be added**:

Add this project here: https://graphql.org/code/#go

**Why is this needed**:

It improves visibility world-wide.

**Comment by kpbird** [comment]
Add super graph in above page and generate a pull request

https://github.com/graphql/graphql.github.io/pull/888

**Comment by frederikhors** [comment]
Amazing! Thanks!

**Comment by frederikhors** [comment]
I think we can close this.

I leave it open so that @dosco can read it.

**Comment by kpbird** [comment]
@frederikhors  I think this ticket should be open until pull request merge

**Comment by tienthanh8490** [comment]
Since you're at it, would be great to add SG to the [awesome-graphql collection](https://github.com/chentsulin/awesome-graphql) too. Awesome-x pages are pretty popular among devs these days.

**Comment by kpbird** [comment]
@tienthanh8490  Pull request generated 
https://github.com/chentsulin/awesome-graphql/pull/602

FYI: @dosco

**Comment by frederikhors** [comment]
@kpbird pull request is closed.

Can I close this?

**Comment by kpbird** [comment]
Yes, Please
