### ISSUE TITLE
where: in: creates invalid sql

### ISSUE THREAD

**Issue by wttw** [dosco/super-graph#123]
### Have you tried reproducing the issue with the latest release?

Yes, bce8a0c

### Steps to reproduce the issue (config used to run Super Graph).

A query using the "in:" operator:
```
{
  tickets(where:{
    urgency: {in: ["Normal", "Urgent"]}
  }) {
    name
  }
}
```

### Expected behaviour and actual result.

I expected a non-error response, but it responds with an error:
```
{
  "error": {
    "error": "ERROR: syntax error at or near \",\" (SQLSTATE 42601)"
  }
}
```

Digging into the SQL generation I expected a sql query like this
```
... where (("ticket"."urgency") IN ('Normal', 'Urgent')) ...
```
or
```
... where (("ticket"."urgency") = ANY(ARRAY['Normal', 'Urgent'])) ...
```

Actual behaviour is to use a sql query like this
```
... where (("ticket"."urgency") = ANY ('Normal', 'Urgent')) ...
```

**Comment by dosco** [comment]
I'll look into this

**Comment by kpbird** [comment]
@dosco As per document it should use In operator but query generates with ANY(Array[]) operator. 

Does it require an update in the document?

Current documentation
in | status: { in: [ "A", "B", "C" ] } | status IN ('A', 'B', 'C')

https://supergraph.dev/docs/graphql/

**Comment by dosco** [comment]
There is no requirement that `in` must be an `in` in the backend the generated SQL does the same thing. Technically all `in` queries are internally converted to `= ANY` queries by Postges. No docs are correct.
