### ISSUE TITLE
Unable to query with schema other than public in lib mode

### ISSUE THREAD

**Issue by pdemacs** [dosco/super-graph#134]
I am getting following error when i change the schema to anything other than "public"

INF attribute based access control disabled: roles_query not set
2020/07/16 18:15:00 error fetching columns: ERROR: syntax error at or near ")" (SQLSTATE 42601)

I am able to make the same query using sg if the schema is "public"
I am also able to make query on the schema not working in sg directly with go sql library.

**Comment by pdemacs** [comment]
Solution was to specify schema at the time of opening db apart from specifying it in config
something like this

	conf := core.Config{
		DBSchema: "your_schema",
		Debug:    true,
	}

	config, _ := pgx.ParseConfig("")
	config.Host = "localhost"
	config.Port = 5432
	config.User = "postgres"
	config.Password = "postgres"
	config.Database = "postgres"
	config.RuntimeParams = map[string]string{
		"search_path": "your_schema",
	}

	connString := stdlib.RegisterConnConfig(config)

db, err := sql.Open("pgx", connString)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

sg, err := core.NewSuperGraph(&conf, db)
	if err != nil {
		log.Fatal(err)
	}

**Comment by dosco** [comment]
Thanks for debugging this. I'll add it to the documentation.
