### ISSUE TITLE
Add support for introspection queries

### ISSUE THREAD

**Issue by dosco** [dosco/super-graph#18]
**What would you like to be added**:

Super Graph currently does not support introspection queries. Introspection queries are used by GraphQL editors to help with auto-complete and other useful features. They help someone building a query know what tables, columns, functions, etc are available to query. We currently use a mocked response to satisfy the GraphQL Playground UI.

The changes to create this would be limited to `serv/introsp.go`. We would need to iterate through the database schema (Global variable `schema`) and built out the introspection response object to en encoded and returned as json. In production mode this feature would need to be disabled.

To learn more
https://graphqlmastery.com/blog/graphql-introspection-and-introspection-queries
https://graphql.org/learn/introspection/

**This is what an introspection query response looks like**

```json
"data":{
   "__schema":{
      "queryType":{
         "name":"Query"
      },
      "mutationType":null,
      "subscriptionType":null
   }
}
}
```

**Why is this needed**:

Will improve our support for GraphQL IDEs. This includes the GraphQL Playground UI that is built in to Super Graph.

**Comment by NikhilVerma** [comment]
@dosco Was this done? We are using graphjin in our project and can't make introspection queries work still.

**Comment by dosco** [comment]
This was added over a year ago. See the webui for an example of the introspection query
