### ISSUE TITLE
Add a health check endpoint

### ISSUE THREAD

**Issue by dosco** [dosco/super-graph#19]
**What would you like to be added**:

Add health check. Currently in production the `/` route does not exists I would like it to serve as a health check endpoint in production mode. It would have to confirm the database connect is working fine and return a 200 or 500 if and failure is detected. This should be a fairly start forward change to implement and be limited to the `serv` package.

**Why is this needed**:

Many cloud environments like Kubernetes, Google Cloud Run, App Engine and several load balancers perform health checks before directing traffic to an instance.

**Comment by lzakharov** [comment]
@dosco, please take a look.

**Comment by dosco** [comment]
Looks great. Add a short response body for the 200 OK and feel free to open a pull request.
