### ISSUE TITLE
Unable to compile as per instructions

### ISSUE THREAD

**Issue by jvijay-work** [dosco/super-graph#30]
### What version of Super Graph are you using? `super-graph version`
Latest source code

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
Ubuntu Bionic

### Steps to reproduce the issue (config used to run Super Graph).
$ go version
go version go1.13.6 linux/amd64
# There is no gopath and goroot environmental variables
$ echo $GOPATH
$ echo $GOROOT
$ make install
package github.com/GeertJohan/go.rice/rice: cannot download, $GOPATH must not be set to $GOROOT. For more details see: 'go help gopath'
Makefile:33: recipe for target '/home/joev/go/bin/github.com/GeertJohan/go.rice' failed
make: *** [/home/joev/go/bin/github.com/GeertJohan/go.rice] Error 1

### Expected behaviour and actual result.
Successful compilation

**Comment by dosco** [comment]
Thanks for the report. There was a bug which caused a generator called go.rice to not be installed. It's now fixed.
