### ISSUE TITLE
panic: file does not exist

### ISSUE THREAD

**Issue by jvijay-work** [dosco/super-graph#32]
### What version of Super Graph are you using? `super-graph version`
Super Graph v0.12.8-1-g76340ab
For documentation, visit https://supergraph.dev

Commit SHA-1          : 76340ab
Commit timestamp      : 2020-01-14 01:08:04 -0500
Branch                : master
Go version            : go1.13.6

Licensed under the Apache Public License 2.0
Copyright 2015-2019 Vikram Rangnekar.

### Have you tried reproducing the issue with the latest release?
Cloned the latest release

### What is the hardware spec (RAM, OS)?
72GB, RHEL 7 OS

### Steps to reproduce the issue (config used to run Super Graph).
$ super-graph new gqlapp
4:46PM INF created 'gqlapp'
4:46PM INF created 'gqlapp/Dockerfile'
4:46PM INF created 'gqlapp/docker-compose.yml'
4:46PM INF created 'gqlapp/config'
4:46PM INF created 'gqlapp/config/dev.yml'
4:46PM INF created 'gqlapp/config/prod.yml'
4:46PM INF created 'gqlapp/config/seed.js'
4:46PM INF created 'gqlapp/config/migrations'
panic: file does not exist

goroutine 1 [running]:
github.com/GeertJohan/go%2erice.(*Box).MustString(...)
        /home/appworld/go/pkg/mod/github.com/!geert!johan/go.rice@v1.0.0/box.go:329
github.com/dosco/super-graph/serv.(*Templ).get(0xc00006be50, 0xd112dd, 0xc, 0x1886480, 0xc00006a130, 0xc00006a130, 0x1da8701, 0x2)
        /home/appworld/super-graph/serv/cmd_new.go:114 +0x205
github.com/dosco/super-graph/serv.cmdNew.func9(0xc0000345a0, 0x25, 0x1886480, 0xc00006a130)
        /home/appworld/super-graph/serv/cmd_new.go:94 +0x43
github.com/dosco/super-graph/serv.ifNotExists(0xc0000345a0, 0x25, 0xc000103c50)
        /home/appworld/super-graph/serv/cmd_new.go:144 +0xb3
github.com/dosco/super-graph/serv.cmdNew(0xc000249180, 0xc00006be30, 0x1, 0x1)
        /home/appworld/super-graph/serv/cmd_new.go:93 +0x7b5
github.com/spf13/cobra.(*Command).execute(0xc000249180, 0xc00006be00, 0x1, 0x1, 0xc000249180, 0xc00006be00)
        /home/appworld/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000139680, 0x1f4d620, 0xd04a55, 0x4)
        /home/appworld/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/appworld/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/dosco/super-graph/serv.Init()
        /home/appworld/super-graph/serv/cmd.go:154 +0xbd0
main.main()
        /home/appworld/super-graph/main.go:8 +0x20

### Expected behaviour and actual result.
Generate app as per documentation

**Comment by dosco** [comment]
Thanks for reporting this it slipped past me on the last refactor. Fixed.
