### ISSUE TITLE
What if it's not a rails app ?

### ISSUE THREAD

**Issue by ghost** [dosco/super-graph#4]
It seems to be graphql a ting as a gateway to REST based systems right ?

So if the Sub system has an openAPI rest interface this could be used to consume any system written in any language ?

**Comment by dosco** [comment]
Super Graph is not like other traditional GraphQL engines that serve only as gateways. Super Graph primary focus is to covert your GraphQL queries into efficient SQL and then run those against your PostgresDB without you having to write any code.

[How to GraphQL with Super Graph](https://supergraph.dev/guide.html#how-to-graphql)

In addition to this if a column in one of your database tables maps to a remote API for example your user has a field `stripe_customer_id` and you'd like to fetch the users stripe payments along with the database query for the user you can can do this.

[Stitching in REST APIs](https://supergraph.dev/guide.html#stitching-in-rest-apis)
