### ISSUE TITLE
Incorrect SQL query using variables for filters

### ISSUE THREAD

**Issue by frederikhors** [dosco/super-graph#42]
I think we have a problem with filters.

Inspired by this: https://github.com/dosco/super-graph/issues/1#issuecomment-477236321

I used this in my `dev.yml`:

```yml
variables:
    account_id: "select account_id from users where id = $user_id"

- name: user
    tables:
        - name: players
            query:
                filters: ["{ account_id: { _eq: $account_id } }"]
```

And I get this error:

```
ERR C:/super-graph/serv/http.go:104 > failed to handle request error="ERROR: invalid input syntax for type bigint: \"select account_id from users where id = 2\" (SQLSTATE 22P02)"
```

```sql
SELECT "_sg_auth_info"."role", (CASE "_sg_auth_info"."role" WHEN 'user' THEN (SELECT json_build_object('player', "__sel_0"."json") as "__root" FROM (SELECT json_build_object('id', "players_0"."id", 'created_at', "players_0"."created_at", 'account_id', "players_0"."account_id", 'amount', "players_0"."amount", 'note', "players_0"."note") AS "json" FROM (SELECT "players"."id", "players"."created_at", "players"."account_id", "players"."amount", "players"."note" FROM "players" WHERE (((("players"."account_id") = 'select account_id from users where id = 2' :: bigint) AND (("players"."id") =  '2' :: bigint))) LIMIT ('1') :: integer) AS "players_0") AS "__sel_0") WHEN 'admin' THEN (SELECT json_build_object('player', "__sel_0"."json") as "__root" FROM (SELECT json_build_object('id', "players_0"."id", 'created_at', "players_0"."created_at", 'account_id', "players_0"."account_id", 'amount', "players_0"."amount", 'note', "players_0"."note") AS "json" FROM (SELECT "players"."id", "players"."created_at", "players"."account_id", "players"."amount", "players"."note" FROM "players" WHERE ((("players"."id") =  '2' :: bigint)) LIMIT ('1') :: integer) AS "players_0") AS "__sel_0") END) FROM (SELECT (CASE WHEN EXISTS (SELECT * FROM users WHERE id = 2) THEN (SELECT (CASE WHEN id = 1000 THEN 'admin' ELSE 'user' END) FROM (SELECT * FROM users WHERE id = 2) AS "_sg_auth_roles_query" LIMIT 1) ELSE 'anon' END) FROM (VALUES (1)) AS "_sg_auth_filler") AS "_sg_auth_info"(role) LIMIT 1
```

The query is visibly incorrect. A bug or is it my fault?

**Comment by frederikhors** [comment]
The problem is this:

```sql
WHERE (((("players"."account_id") = 'select account_id from users where id = 2' :: bigint)...
```

should be:


```sql
WHERE (((("players"."account_id") = (select account_id from users where id = 2) :: bigint)...
```

**Comment by dosco** [comment]
Using variables in that way has been deprecated. I need to remove this from the example app config file. What you want to achieve can be done using nested where clauses. https://supergraph.dev/guide.html#nested-where-clause-targeting-related-tables

Below should return all the players who have a related user with the current user id.

```
query {
  players(where: { 
      users: { id: { eq: $user_id } }
    }) {
    id
    name
  }
}
```

**Comment by frederikhors** [comment]
> Using variables in that way has been deprecated. I need to remove this from the example app config file.

Ok. I will remember you by keeping this issue open.

> What you want to achieve can be done using nested where clauses.

This is not what I need.

I have an `accounts` table with columns: `id - description`

and a `users` table with columns: `id - description - account_id`.

I'm using the `{"X-User-ID": 3}` which has `account_id = 2`.

Using this filter in yml:

```yml
- name: users
  query:
    filters: ["{ accounts: { id: { eq: $user_id } } }"]
```

compiles this query:

```sql
SELECT
  "users"."id",
FROM
  "users" 
WHERE
  (
    EXISTS (
    SELECT
      1 
    FROM
      accounts 
    WHERE
      ( ( "accounts"."id" ) = ( "users"."account_id" ) ) 
      AND ( ( ( "accounts"."id" ) = '3' :: BIGINT ) ) 
    ) 
  )
```

which is wrong because I need

```sql
AND ( ( ( "accounts"."id" ) = '2' :: BIGINT ) ) 
```

so `2` instead of `3`.

Is my need clearer now?

**Comment by dosco** [comment]
I noticed you mentioned `players` earlier is this a separate table or is it the same as `users`.  Could you explain what you are trying to fetch? Are you fetching users and their related accounts or all accounts and their users? 

This `["{ accounts: { id: { eq: $user_id } } }"]` would obviously not work as it translates into ` account.id = $user_id` which is clearly incorrect.

If you want to fetch a user with the id `3` and his account then just do

```
user(id: 3) {
  id
  description
  account{
    id
    description
  }
}
```

**Comment by frederikhors** [comment]
Ok. Sorry for the lack of clarity.

My DB relation is like this:

![image](https://user-images.githubusercontent.com/41120635/75354067-ac815e00-58ac-11ea-9252-4332f392115c.png)

Each table has a `company_id` (or `account_id`, whatever) and I need to filter each table by `company_id`.

So in english I need to:

1. find the `company_id` for my `user_id` (a column in `users` table)
1. filter each table (e.g. `players`) by that `company_id`.

Is my need clearer now?

**Comment by dosco** [comment]
`Employee.CompanyId` should be a foreign key relationship to `Company.CompanyID` the you can just do what I mentioned above. If for some reason you don't have this relationship (I recommend creating it) you can create this relationship in the config file as shown below.

```
employee(id: 3) {
  fullname
  company{
    title
  }
}
```

Creating relationships between tables using your config instead of in the DB. https://supergraph.dev/guide.html#database-relationships

```
tables:
  - name: employee
    columns:
      - name: companyid
        related_to: company.companyid
```

**Comment by frederikhors** [comment]
@dosco, I'm talking about filters in config yml, not queries.

> - name: user
>     tables:
>         - name: players
>             query:
>                 filters: ["{ account_id: { _eq: $account_id } }"]

> The problem is this:
> 
> ```sql
> WHERE (((("players"."account_id") = 'select account_id from users where id = 2' :: bigint)...
> ```
> 
> should be:
> 
> 
> ```sql
> WHERE (((("players"."account_id") = (select account_id from users where id = 2) :: bigint)...
> ```

**Comment by dosco** [comment]
I understood that part and like I said we have **removed** that feature to use SQL in variables. I don't want people to have to turn to SQL when Super Graph GraphQL can easily do this for them. 

To me it seems your main issue is that that you don't have a relationship (foreign key or config based) between these two tables. Please create this relationship and everything will work fine. You don't need SQL.

Also in this case it seems you have three tables `players`, `accounts` and `users` so you will need foreign key (or config) based relationships between these three tables for Super Graph to work properly. 

```
query users(id: 2) {
   account {
      players {
         
      }
   }
}
```

**Comment by frederikhors** [comment]
I understand everything you say and I also believe that my DB has the structure you say (_see below my DB structure_).

What we are not understanding is what I want to achieve.

**I don't want to use queries to filter user's players.**

I want SuperGraph to automatically filter every query and mutation based on a principle:

1. each user belongs to an account (`users.account_id`)
1. each user has many players
1. many users can have the same `account_id`
1. each player belong to an account (`players.account_id`)
1. SuperGraph must filter all queries for the player's `account_id` automatically (in background) and **not manually** with the query created by me

### Examples tables

**Users** table:

```
+----+------------+-----------------+
| id | account_id |      email      |
+----+------------+-----------------+
|  1 |        100 | user1@email.com |
|  2 |        200 | user2@email.com |
|  3 |        300 | user3@email.com |
+----+------------+-----------------+
```

**Players** table:

```
+----+------------+------+
| id | account_id | name |
+----+------------+------+
|  1 |        100 | John |
|  2 |        100 | Mac  |
|  3 |        200 | Bill |
+----+------------+------+
```

### Example 1

I'm logged in as: `X-User-ID: 2` (so the `account_id` is: 200).

This query below must filter my players for the user's `account_id`.

```graphql
query players {
    id
    account_id
    name
}
```

My expected result is:

```json
{
    "players": [
        {
            "id": "3",
            "account_id": "200",
            "name": "Bill"
        }
    ]
}
```

### Example 2

With the same tables if I'm logged in as: `X-User-ID: 1` (so the `account_id` is: 100) I expect below data from **the same query** above:

```json
{
    "players": [
        {
            "id": "1",
            "account_id": "100",
            "name": "John"
        },
        {
            "id": "2",
            "account_id": "100",
            "name": "Mac"
        }
    ]
}
```

### My DB structure

Are there all the foreign keys you were talking about?

```sql
DROP TABLE IF EXISTS "public"."players";
CREATE TABLE "public"."players" (
  "id" int8 NOT NULL,
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6),
  "account_id" int8 NOT NULL,
  "name" text COLLATE "pg_catalog"."default"
)
;

DROP TABLE IF EXISTS "public"."accounts";
CREATE TABLE "public"."accounts" (
  "id" int8 NOT NULL,
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6),
  "description" text COLLATE "pg_catalog"."default"
)
;

DROP TABLE IF EXISTS "public"."users";
CREATE TABLE "public"."users" (
  "id" int8 NOT NULL,
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6),
  "account_id" int8 NOT NULL,
  "email" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "password" text COLLATE "pg_catalog"."default" NOT NULL,
  "username" varchar(100) COLLATE "pg_catalog"."default",
)
;

ALTER TABLE "public"."players" ADD CONSTRAINT "players_pkey" PRIMARY KEY ("id");

ALTER TABLE "public"."accounts" ADD CONSTRAINT "accounts_pkey" PRIMARY KEY ("id");

ALTER TABLE "public"."users" ADD CONSTRAINT "users_email_key" UNIQUE ("email");
ALTER TABLE "public"."users" ADD CONSTRAINT "users_username_key" UNIQUE ("username");
ALTER TABLE "public"."users" ADD CONSTRAINT "users_email_username_key" UNIQUE ("email", "username");

ALTER TABLE "public"."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");

ALTER TABLE "public"."players" ADD CONSTRAINT "players_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "public"."users" ADD CONSTRAINT "users_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
```

**Comment by dosco** [comment]
Thanks that makes things a lot clearer. Let me think about it.

**Comment by dosco** [comment]
FYI working on a fix

**Comment by dosco** [comment]
Fixed in https://github.com/dosco/super-graph/commit/a1fb89b7629e64dd597637b6f0d675a9b5134597 please prefix the variable value with `sql:`

```
variables:
    account_id: "sql:select account_id from users where id = $user_id"
```

**Comment by dosco** [comment]
@frederikhors  if this works for you i'll close this issue

**Comment by frederikhors** [comment]
It works now.

We should change/add to docs, right?
