### ISSUE TITLE
hasNextPage field for cursor pagination

### ISSUE THREAD

**Issue by frederikhors** [dosco/super-graph#44]
Has https://supergraph.dev/guide.html#cursor pagination a `hasNextPage` field?

**Comment by dosco** [comment]
The cursor value is `null` when you reach the end of the table. Example below
`{"data":{"posts":[],"posts_cursor":null}}`

**Comment by frederikhors** [comment]
Mmm.

Let's say I have 10 rows in my table.

I use this query:

```graphql
{
  players(first: 10) {
    id
    score
  }
}
```

SuperGraph gives me a cursor. And I think it's wrong. Because every client understands there is a `nextPage` which is false, right?

**Comment by dosco** [comment]
Cursor pagination is designed to be a fast way to paginate large tables when building something like infinite scroll. The above table will return a cursor that you return back along with the next query and so on. If there is no more data left in the table then you will get an empty array back and a null cursor. 

I'm not sure what client you're referring to you can just use something like [graphql.js ](https://supergraph.dev/guide.html#graphql-with-react) which will handle this fine. The most you will do is make one extra query.

Alternatively you can always use a `count` [aggregation](https://supergraph.dev/guide.html#aggregations) to count total rows and then keep track of how many you've loaded using pagination. But doing this means you will miss any additional rows that get added while you are paginating through the table.

```
{
  players(first: 10, after: $cursor) {
    id
    score
  }
}
```
