### ISSUE TITLE
Order_by ID

### ISSUE THREAD

**Issue by frederikhors** [dosco/super-graph#45]
I think there is a problem with order_by ID.

I'm trying this query:

```graphql
{
  players(first: 5, after: $cursor, order_by: {id: desc}) {
    id
    score
  }
}
```

decrypted cursor is: `4695` (the ID)

and the query it generates is:

```sql
SELECT json_build_object('players', "__sel_0"."json", 'players_cursor', "__sel_0"."cursor") as "__root" FROM (SELECT coalesce(json_agg("__sel_0"."json"), '[]') as "json", CONCAT_WS(',', max("__cur_0")) as "cursor" FROM (SELECT json_build_object('id', "players_0"."id", 'score', "players_0"."score") AS "json", LAST_VALUE("players_0"."id") OVER() AS "__cur_0" FROM (WITH "__cur" AS (SELECT a[1] as "id" FROM string_to_array('4695', ',') as a) SELECT "players"."id", "players"."score" FROM "players", "__cur" ORDER BY "players"."id" DESC LIMIT ('5') :: integer) AS "players_0") AS "__sel_0") AS "__sel_0"
```

As you can see there is no `WHERE` clause for cursor.

If I use this query:

```graphql
{
  players(first: 5, after: $cursor, order_by: {created_at: desc}) {
    id
    score
  }
}
```

decrypted cursor is: `2020-02-27 12:21:23.282411+00,4695`

and the query it generates is:

```sql
SELECT json_build_object('players', "__sel_0"."json", 'players_cursor', "__sel_0"."cursor") as "__root" FROM (SELECT coalesce(json_agg("__sel_0"."json"), '[]') as "json", CONCAT_WS(',', max("__cur_0"), max("__cur_1")) as "cursor" FROM (SELECT json_build_object('id', "players_0"."id", 'score', "players_0"."score") AS "json", LAST_VALUE("players_0"."created_at") OVER() AS "__cur_0", LAST_VALUE("players_0"."id") OVER() AS "__cur_1" FROM (WITH "__cur" AS (SELECT a[1] as "created_at", a[2] as "id" FROM string_to_array('2020-02-27 12:21:23.282411+00,4695', ',') as a) SELECT "players"."id", "players"."score", "players"."created_at" FROM "players", "__cur" WHERE (((("players"."created_at") < "__cur"."created_at" :: timestamp with time zone) OR ((("players"."created_at") = "__cur"."created_at" :: timestamp with time zone) AND (("players"."id") > "__cur"."id" :: bigint)))) ORDER BY "players"."created_at" DESC, "players"."id" ASC LIMIT ('5') :: integer) AS "players_0") AS "__sel_0") AS "__sel_0"
```

It is working correctly.

So... something strange, right?

Is order_by ID working?

**Comment by dosco** [comment]
This should not happen thanks for the issue I'll fix this. In the meanwhile what you are trying to do can be achieved by the below query. This will automatically order by primary key `id` in `desc` order since you are asking for `last: 10`

```
{
  players(last: 10, before: $cursor) {
    id
    score
  }
}

**Comment by frederikhors** [comment]
I think there is something strange here.

If I use the query you wrote is like I'm asking to SuperGraph:

"Please, list me the last 10 players in DB block that starts after the bookmark `$cursor` and ends at the end of the list. But please **list me players in ORDER BY id ASC, NOT DESC**."

Am I totally wrong?

**Comment by frederikhors** [comment]
If you change from ASC to DESC based on graphql query `first` and `last` it seems strange to me.

**Comment by frederikhors** [comment]
If you run Postgraphile (www.graphile.org) with:

```console
npx postgraphile --subscriptions --watch --dynamic-json --no-setof-functions-contain-nulls --no-ignore-rbac --no-ignore-indexes --show-error-stack=json --extended-errors hint,detail,errcode --graphiql "/" --enhance-graphiql --allow-explain --enable-query-batching --legacy-relations omit --connection postgres://postgres:postgres@localhost/your_db?sslmode=disable
```

in fact, the behavior is different.

But still strange I think.

If you ask it for:

```graphql
query {
  allPlayers(last: 5) {
    nodes {
      id
    }
  }
}
```

it will list last five ASC ordinated. E.g. from 1-100: `96-97-98-99-100`.

If I ask with this query:

```graphql
query {
  allPlayers(last: 5, orderBy: ID_DESC) {
    nodes {
      id
    }
  }
}
```

it will list `5-4-3-2-1`.

If I'm looking for `100-99-98-97-96` I need to use `first` as:

```graphql
query {
  allPlayers(first: 5, orderBy: ID_DESC) {
    nodes {
      id
    }
  }
}
```

Strange, right?

I think the world needs a convention here!

**Comment by dosco** [comment]
I think wha you are doing here is over writing the order by in postgraphile using the `orderBy` clause. In Super Graph `first` means from the top of the table according to the natural order of rows as it should. And `last` is from the bottom. Super Graph automatically manages the order by clause internally.
