### ISSUE TITLE
Support TLS connections

### ISSUE THREAD

**Issue by chirino** [dosco/super-graph#49]
**What would you like to be added**:

Using a TLS connection to the DB.

**Why is this needed**:

For improved security in this day of cloud infrastructure.

**Comment by dosco** [comment]
If you're using Super Graph as a library then you can configure that in your code. As for Super Graph as a service I agree it should support that and probably would not be too hard to add. Super Graph uses the `pgx` driver for Postgres.

**Comment by dosco** [comment]
Committed several fixes that you might appreciate. Added TLS config for database connections and moved things around so `go get github.com/dosco/super-graph` can be used to download and install the binary. https://github.com/dosco/super-graph/commit/09d6460a133f7812f178dd893879cff8878c0be6

```
  # Set up an secure tls encrypted db connection
  enable_tls: false

  # Required for tls. For example with Google Cloud SQL it's
  # <gcp-project-id>:<cloud-sql-instance>"
  server_name: blah

  # Required for tls. Can be a file path or the contents of the pem file
  server_cert: ./server-ca.pem

  # Required for tls. Can be a file path or the contents of the pem file
  client_cert: ./client-cert.pem

  # Required for tls. Can be a file path or the contents of the pem file
  client_key: ./client-key.pem
```
