### ISSUE TITLE
Error reading metadata

### ISSUE THREAD

**Issue by howesteve** [dosco/super-graph#65]
Hello,

Still trying to make embedded mode work. SuperGraph instance initilization fails when loading metadata from the server; inside GetFunctions(), this line is called:
```go
err = rows.Scan(&fn, &fid, &fp.Type, &fp.Name, &fp.ID)
```
and the following error is returned:
```
sql: Scan error on column index 3, name "parameter_name": converting NULL to string is unsupported
```
The internal query, which reads from information_schema.routines, is returned successfully. The problem is scanning the data from that column "parameter_name".

I'm guessing this could be due to internally changing from pgx driver to the stdlib one, which does not support scanning from null to string? Their recommendation in that case would be using sql.NullString, sql.NullInt32, etc. But that would require some major refactoring in source code on all those metadata structures.

I could be doing something silly here, otherwise it seems to me that others would be having the same error?

**Comment by dosco** [comment]
Are you running the latest code? We recently merged a PR that fixes a very similar issue. The `Name` field in the `DBFuncParam` struct was changed to be `Name sql.NullString` https://github.com/dosco/super-graph/pull/60

**Comment by howesteve** [comment]
Ah, that was it. I apologize. I was on v0.13.23, and had a "go get -u" so thought everything was up to date. Had to delete v0.13.23 manually and now on v0.13.25 it's loading.

Thanks.
