### ISSUE TITLE
Super Graph returns a row instance when the table name is singular

### ISSUE THREAD

**Issue by FourSigma** [dosco/super-graph#7]
```
query {
  actor {
    actor_id
    first_name
    last_name
  }
}
```

## Expected Behaviour

Should return an array of actors.
```
{
  "data": {
    "actor": [{
      "actor_id": 1,
      "first_name": "Penelope",
      "last_name": "Guiness"
    },
    {...},
    {...}]
  }
}

```

## Actual Behavior

Returns *one* instance of an actor.

```
{
  "data": {
    "actor": {
      "actor_id": 1,
      "first_name": "Penelope",
      "last_name": "Guiness"
    }
  }
}
```

## Steps to Reproduce the Problem

  1.  The behaviour happens when the table name is singular (actor vs actors).
  2.  `ALTER TABLE actor RENAME TO actors` fixes the issue 

## Misc
I built super graph from the source code, ran `go build . ` modified the the dev.yaml file

**Comment by dosco** [comment]
That a feature the name used in the GraphQL selector does not directly map to the database table so if you use `actor` you will only get 1 value for all use `actors`. Your table name can be either.

`
query {
  actors {
    actor_id
  }
}`

**Comment by FourSigma** [comment]
I downloaded and re-compiled it is working now!
