### ISSUE TITLE
ReadInConfig folder path not work

### ISSUE THREAD

**Issue by lulucas** [dosco/super-graph#73]
### What version of Super Graph are you using? `super-graph version`

v0.14.10

### Steps to reproduce the issue (config used to run Super Graph).
```
package main

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/dosco/super-graph/core"
	_ "github.com/jackc/pgx/v4/stdlib"
	"log"
)

func main() {
	db, err := sql.Open("pgx", "postgres://postgres:postgres@localhost:5432/api_development")
	if err != nil {
		log.Fatal(err)
	}

	conf, err := core.ReadInConfig("./config/dev.yml")
	if err != nil {
		log.Fatalln(err)
	}

	sg, err := core.NewSuperGraph(conf, db)
	if err != nil {
		log.Fatalln(err)
	}

	query := `
		query {
			users {
				id
				name
			}
		}`
	ctx := context.Background()
	ctx = context.WithValue(ctx, core.UserIDKey, 1)
	res, err := sg.GraphQL(ctx, query, nil)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(string(res.Data))
}
```

### Expected behaviour and actual result.

core.ReadInConfig("./config/dev.yml") 

It actually read `dev.yml` not `./config/dev.yml`, folder not included in path.

2020/06/07 12:05:00 open dev.yml: The system cannot find the file specified.

**Comment by lulucas** [comment]
core.ReadInConfig("./dev")  works, depends on GetConfigName code, but it's internal.

**Comment by dosco** [comment]
This function needs a bit of a cleanup it should accept paths with extensions.

**Comment by dosco** [comment]
FYI fix is in.
