### ISSUE TITLE
Getting error while trying to login to rail app.

### ISSUE THREAD

**Issue by asharabu** [dosco/super-graph#75]
Hi,

I have deployed supergraph, postgres and rails app using https://github.com/dosco/super-graph/blob/master/docker-compose.yml but when I try to sign up rail app getting error. Can you please let me know the default login for this rails app.

> 

ActiveRecord::NotNullViolation in Devise::RegistrationsController#create
PG::NotNullViolation: ERROR: null value in column "full_name" violates not-null constraint DETAIL: Failing row contains (37, null, null, null, test@test.com, $2a$11$z6h2KUZYGLJz3Otr3BBtoOm8ID.LNPM6bx9qn.zZ12dyOx/EbspMC, null, null, null, 2020-06-15 14:55:10.488498, 2020-06-15 14:55:10.488498).

>

**Comment by dosco** [comment]
https://supergraph.dev/docs/intro#try-the-demo-app
`# signin to the demo app (user1@demo.com / 123456)`
