### ISSUE TITLE
Escape characters in debug console logs make it harder to read

### ISSUE THREAD

**Issue by FourSigma** [dosco/super-graph#8]
It is hard to read the SQL in the debug logs when  escape characters are present (`\n`, `\t`, and `\"`).

` Query args=["public","sales_by_store"] module=pgx pid=23073 rowCount=0 sql="\nSELECT  \n\tf.attnum AS id,  \n\tf.attname AS name,  \n\tf.attnotnull AS notnull,  \n\tpg_catalog.format_type(f.atttypid,f.atttypmod) AS type,  \n\tCASE  \n\t\tWHEN p.contype = ('p'::char) THEN true  \n\t\tELSE false \n\tEND AS primarykey,  \n\tCASE  \n\t\tWHEN p.contype = ('u'::char) THEN true  \n\t\tELSE false\n\tEND AS uniquekey,\n\tCASE\n\t\tWHEN p.contype = ('f'::char) THEN g.relname \n\t\tELSE ''::text\n\tEND AS foreignkey,\n\tCASE\n\t\tWHEN p.contype = ('f'::char) THEN p.confkey\n\t\tELSE ARRAY[]::int2[]\n\tEND AS foreignkey_fieldnum\nFROM pg_attribute f\n\tJOIN pg_class c ON c.oid = f.attrelid  \n\tLEFT JOIN pg_attrdef d ON d.adrelid = c.oid AND d.adnum = f.attnum  \n\tLEFT JOIN pg_namespace n ON n.oid = c.relnamespace  \n\tLEFT JOIN pg_constraint p ON p.conrelid = c.oid AND f.attnum = ANY (p.conkey)  \n\tLEFT JOIN pg_class AS g ON p.confrelid = g.oid  \nWHERE c.relkind = ('r'::char)\n\tAND n.nspname = $1  -- Replace with Schema name  \n\tAND c.relname = $2  -- Replace with table name  \n\tAND f.attnum > 0\n\tAND f.attisdropped = false\nORDER BY id;" `

**Comment by dosco** [comment]
I agree unfortunately it's a side effect of  using the tagged (key="value") log format of the zerolog logging library. I'll look into what options it gives towards fixing this. You might not see this if you downgrade the log level in the config. Seeing the actual query is only useful when debugging and the default log level is "debug"

**Comment by dosco** [comment]
Fixed in the RBAC branch. Will merge it in a couple days.
