### ISSUE TITLE
"data" field in JSON response using SuperGraph as library

### ISSUE THREAD

**Issue by frederikhors** [dosco/super-graph#83]
Using [SuperGraph](https://github.com/dosco/super-graph) as library I found JSON responses does not start with: `"data"`.

Example:

```json
{
  "players": [...]
}
```

instead of:

```json
{
  "data": {
    "players": [...]
  }
}
```

I'm using this code:

```go
func main() {
	sg, err := core.NewSuperGraph(nil, sb)

	r := chi.NewRouter()

	r.Group(func(r chi.Router) {
		r.Post(config.ApiEndpoint, myHandler(sg))
	})

	StartServer(r)
}

type reqBody struct {
	Query string `json:"query"`
}

func sgHandler(sg *core.SuperGraph, next http.Handler) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var rBody reqBody
		bodyBytes, _ := ioutil.ReadAll(r.Body)
		_ = r.Body.Close(
		r.Body = ioutil.NopCloser(bytes.NewBuffer(bodyBytes))
		err := json.NewDecoder(bytes.NewBuffer(bodyBytes)).Decode(&rBody)
		if err != nil {
			http.Error(w, "Error parsing JSON request body", 400)
		}

		res, err := sg.GraphQL(ctx, rBody.Query, nil)
		if err == nil {
			result, _ := json.Marshal(res.Data) // IS THIS WRONG?
			_, err = w.Write(result)
		}
	}
}
```

Is it my fault?

Is this wrong? `result, _ := json.Marshal(res.Data)`?

Maybe I need to Marshal all `res`? Isn't it heavier?

**Comment by frederikhors** [comment]
My bad. Sorry.

**Comment by dosco** [comment]
The `GraphQL` function produces a `Result` object if you encode (marshall) that to json then you'll get a data object among other things the Data field of the `Result` struct is only the pure JSON value.

**Comment by frederikhors** [comment]
@dosco I updated the question. I can't fix it. I'm writing a sample project and I need to understand how to optimize these lines.

**Comment by frederikhors** [comment]
Sorry I was totally wrong. I need to marshal `res`. I understand now.
