### ISSUE TITLE
SG as library: Vars config, filter panic: interface conversion: interface {} is int, not string

### ISSUE THREAD

**Issue by frederikhors** [dosco/super-graph#86]
Remember the problem solved here: https://github.com/dosco/super-graph/issues/42, @dosco?

Now I'm using SuperGraph as library with this code:

```go
sgConfig := core.Config{
  DefaultBlock: true,
  Vars: map[string]string{
    "account_id": "sql:select account_id from users where id = $user_id",
  },
  Roles: []core.Role{
    {
      Name: "user",
      Tables: []core.RoleTable{
        {
          Name: "players",
          Query: &core.Query{
            Filters: []string{
              "{ account_id: { _eq: $account_id } }",
            },
          },
        },
      },
    },
  },
}
sg, err := core.NewSuperGraph(&sgConfig, db)
```

it doesn't work!

This is the error:

```log
panic: interface conversion: interface {} is int, not string

-> github.com/dosco/super-graph/core.(*scontext).argList
->   C:/fred/go/pkg/mod/github.com/dosco/super-graph@v0.14.30/core/args.go:33

github.com/dosco/super-graph/core.(*scontext).resolveSQL
  C:/fred/go/pkg/mod/github.com/dosco/super-graph@v0.14.30/core/core.go:272
github.com/dosco/super-graph/core.(*scontext).execQuery
  C:/fred/go/pkg/mod/github.com/dosco/super-graph@v0.14.30/core/core.go:121
github.com/dosco/super-graph/core.(*SuperGraph).GraphQL
  C:/fred/go/pkg/mod/github.com/dosco/super-graph@v0.14.30/core/api.go:202
main.sgHandler.func1
```

**What is wrong?**

**Comment by frederikhors** [comment]
I found the issue, reading your code here:



I was passing an `int` and not a `string` for `UserIDKey` value in context, with this code:

```go
ctx := context.WithValue(r.Context(), core.UserIDKey, authentication.MyID()) // int
```

Now I'm using this instead:

```go
ctx := context.WithValue(r.Context(), core.UserIDKey, strconv.Itoa(authentication.MyID()))
```

At first I didn't notice the error because nowhere is it written that it must be a string.

Shall we create a page for `config` and "using SuperGraph as a library" related?

Can we specify it in code docs? Do you agree, @dosco?

![image](https://user-images.githubusercontent.com/41120635/85960037-9b527600-b9a0-11ea-9924-1107e7b67c49.png)

**Comment by dosco** [comment]
Thanks that would be very valuable if you could document your experience with using Super Graph as a library. You can add a page to this folder and i'll include it on the website. https://github.com/dosco/super-graph/tree/master/docs/website/docs

**Comment by frederikhors** [comment]
Yes I'll create a page in a few hours.

For this problem, **can we use both `string` and `int` for `user_id`?**

Here the code (https://github.com/dosco/super-graph/blob/master/core/args.go#L29-L36):

```go
for i, p := range params {
  switch p.Name {
  case "user_id":
    if v := c.Value(UserIDKey); v != nil {
      vars[i] = v.(string) // maybe a case for int too?
    } else {
      return nil, argErr(p)
    }
...
```

**Comment by dosco** [comment]
That should work.

**Comment by dosco** [comment]
Fixed in https://github.com/dosco/super-graph/commit/9c19db2ed59b8911f3f0bc438728eebfbbd045a2
