### ISSUE TITLE
Blocklist only block queries with singular name and not plural and the other way around

### ISSUE THREAD

**Issue by frederikhors** [dosco/super-graph#89]
### What version of Super Graph are you using?

Latest master version using go.mod, SuperGraph as a library.

### Steps to reproduce the issue (config used to run Super Graph).

Using this code:

```go
Blocklist: []string{
  "players",
},
```

### Expected behaviour and actual result.

Querying with:

```graphql
query players {
  players {
    id
    name
  }
}
```

is working because I get `HTTP 200` with an empty body.

But if I query with:

```graphql
query player {
  player {
    id
    name
  }
}
```

**I get the first one!** (ordered by `ID ASC`).

I think it should also block the query with the singular name, right?

**Comment by dosco** [comment]
It should this is a bug. I'll look into it. For now you can block queries at the role config level and limit this top level blocklist for column names.

**Comment by dosco** [comment]
Fixed in https://github.com/dosco/super-graph/commit/9c19db2ed59b8911f3f0bc438728eebfbbd045a2
