### ISSUE TITLE
Blocked tables and columns should not appear in introspection info

### ISSUE THREAD

**Issue by frederikhors** [dosco/super-graph#90]
I think blocked tables and columns (with `Blocklist: []string{}` config) should not appear in introspection info.

Am I wrong?

**Comment by dosco** [comment]
I agree the core idea behind this feature was to not leak anything by accident so columns like `credit_card_number` can be blocked by default. I'll make this a bug

**Comment by dosco** [comment]
Fixed in https://github.com/dosco/super-graph/commit/9c19db2ed59b8911f3f0bc438728eebfbbd045a2
