### ISSUE TITLE
__typename form

### ISSUE THREAD

**Issue by frederikhors** [dosco/super-graph#92]
The GraphQL servers I've always used respond to the `__typename` with the singular form capital of the table name.

With SuperGraph, however, this is not the case because the answer is the name of the table itself, which with libraries like [URQL](https://github.com/FormidableLabs/urql) creates havoc and nothing works anymore:

```log
urql-exchange-graphcache.mjs:58:
Heuristic Fragment Matching: A fragment is trying to match against the `players` type, but the type condition is `Player`.
Since GraphQL allows for interfaces `Player` may be an interface.
```

What do you think?

**Can we do it automatically** or do we need to add a field in the config of the single entity?

**Comment by frederikhors** [comment]
I was wrong about URQL and `__typename` but maybe we still need this. I'll leave it open for now.

**Comment by dosco** [comment]
This is so you can can create and use synthetic tables like a `me` tables with limits to only return your own user and since __typename will return `users` the client side caching will know what type of data it is. I use this with Apollo extensively and it works great. Checkout https://abtcode.com as an example.

**Comment by powellamaranth** [comment]
Seems like https://abtcode.com is down.
Tried to install abtcode app from marketplace  to check it out - however NXDOMAIN error.
Upon further digging: domain has only NS and SOA records...

```
id 63223
opcode QUERY
rcode NOERROR
flags QR RD RA
QUESTION
ABTCODE.COM. IN ANY
ANSWER
ABTCODE.COM. 21599 IN SOA ns-cloud-a1.googledomains.COM. cloud-dns-hostmaster.google.COM. 6 21600 3600 259200 300
ABTCODE.COM. 21599 IN NS ns-cloud-a4.googledomains.COM.
ABTCODE.COM. 21599 IN NS ns-cloud-a3.googledomains.COM.
ABTCODE.COM. 21599 IN NS ns-cloud-a1.googledomains.COM.
ABTCODE.COM. 21599 IN NS ns-cloud-a2.googledomains.COM.
AUTHORITY
ADDITIONAL
```
