### ISSUE TITLE
"super-graph new" HTML escapes generated configuration files

### ISSUE THREAD

**Issue by wttw** [dosco/super-graph#95]
### What version of Super Graph are you using? `super-graph version`

"unknown-version"

git describe says v0.11-210-gcd7f26b

### Steps to reproduce the issue (config used to run Super Graph).

`super-graph new app`

### Expected behaviour and actual result.

config/seed.js and config/migrations/o_init.sql are generated HTML escaped

e.g.

expected:
```
for (i = 0; i < 10; i++) {
```
actual:
```
for (i = 0; i &lt; 10; i++) {
```

It looks like internal/serv/cmd_new.go should be importing text/template instead of html/template

https://github.com/dosco/super-graph/blob/master/internal/serv/cmd_new.go#L5

**Comment by dosco** [comment]
Fix in https://github.com/dosco/super-graph/commit/5f4f2e0dc0ff3f9ec17f74755ac029b83e2a6d65
