### ISSUE TITLE
Print query running SuperGraph as a library.

### ISSUE THREAD

**Issue by frederikhors** [dosco/super-graph#98]
Using SuperGraph as a library it's impossible to print the query also after setting `Config{Debug: true}`.

Am I wrong?

I also can't find this config in Go library but I can on Docs page for SG standalone:

```yml
# debug, error, warn, info
log_level: "debug"
```

**Comment by dosco** [comment]
The `GraphQL` function results a result object just called `.SQL()` on it, there are several other methods for other data too. The `Debug` config value it to enable internal debug logging to the console.
